# Generated by Django 4.2.16 on 2025-01-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProba',
            fields=[
                ('patient_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('years', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('years', models.PositiveIntegerField(blank=True, null=True)),
                ('probe_date', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('arterial_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('gw', models.IntegerField(blank=True, null=True)),
                ('baby_weight', models.IntegerField(blank=True, null=True)),
                ('erythrocytes', models.FloatField(blank=True, null=True)),
                ('hemoglobin', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('birth_year', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sex', models.CharField(max_length=10)),
                ('fvl', models.CharField(max_length=3, null=True)),
                ('prothr', models.CharField(max_length=3, null=True)),
                ('pai', models.CharField(max_length=3, null=True)),
                ('mthfr', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
