# Generated by Django 4.2.16 on 2025-01-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PridaMutations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('birth_year', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fvl_ng', models.CharField(max_length=3, null=True)),
                ('fvl_hetero', models.CharField(max_length=3, null=True)),
                ('fvl_homo', models.CharField(max_length=3, null=True)),
                ('prothr_ng', models.CharField(max_length=3, null=True)),
                ('prothr_hetero', models.CharField(max_length=3, null=True)),
                ('prothr_homo', models.CharField(max_length=3, null=True)),
                ('pai_ng', models.CharField(max_length=3, null=True)),
                ('pai_hetero', models.CharField(max_length=3, null=True)),
                ('pai_homo', models.CharField(max_length=3, null=True)),
                ('mthfr_ng', models.CharField(max_length=3, null=True)),
                ('mthfr_hetero', models.CharField(max_length=3, null=True)),
                ('mthfr_homo', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
