# Generated by Django 4.2.16 on 2025-01-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0003_alter_pridamutations_fvl_hetero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridamutations',
            name='pai_hetero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pridamutations',
            name='pai_homo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
