# Generated by Django 4.2.16 on 2025-01-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0004_alter_pridamutations_pai_hetero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pridamutations',
            name='mthfr_hetero',
        ),
        migrations.RemoveField(
            model_name='pridamutations',
            name='mthfr_homo',
        ),
        migrations.RemoveField(
            model_name='pridamutations',
            name='mthfr_ng',
        ),
        migrations.RemoveField(
            model_name='pridamutations',
            name='pai_hetero',
        ),
        migrations.RemoveField(
            model_name='pridamutations',
            name='pai_homo',
        ),
    ]
