# Generated by Django 4.2.16 on 2025-01-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0005_remove_pridamutations_mthfr_hetero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pridamutations',
            name='pai_hetero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
