# Generated by Django 4.2.16 on 2025-01-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0006_pridamutations_pai_hetero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pridamutations',
            name='pai_homo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
