# Generated by Django 4.2.16 on 2025-01-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0007_pridamutations_pai_homo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pridamutations',
            name='mthfr_hetero',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pridamutations',
            name='mthfr_homo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pridamutations',
            name='mthfr_ng',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
