# Generated by Django 4.2.16 on 2025-01-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0008_pridamutations_mthfr_hetero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridamutations',
            name='age',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
    ]
