# Generated by Django 4.2.16 on 2025-01-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0011_alter_pridamutations_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridamutations',
            name='id',
            field=models.PositiveSmallIntegerField(default=0, primary_key=1, serialize=False),
        ),
    ]
