# Generated by Django 4.2.16 on 2025-01-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0012_alter_pridamutations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridamutations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
