# Generated by Django 4.2.16 on 2025-02-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0014_pridamutations_pregnancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pridamutations',
            name='birth_year',
        ),
    ]
