# Generated by Django 4.2.16 on 2025-02-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0015_remove_pridamutations_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridamutations',
            name='pregnancy',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
