# Generated by Django 4.2.16 on 2025-02-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0016_alter_pridamutations_pregnancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pridamutations',
            old_name='pregnancy',
            new_name='abort',
        ),
    ]
