# Generated by Django 4.2.16 on 2025-05-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0017_rename_pregnancy_pridamutations_abort'),
    ]

    operations = [
        migrations.CreateModel(
            name='PridaControli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('fvl_ng', models.CharField(blank=True, max_length=3, null=True)),
                ('fvl_hetero', models.CharField(blank=True, max_length=3, null=True)),
                ('fvl_homo', models.CharField(blank=True, max_length=3, null=True)),
                ('prothr_ng', models.CharField(blank=True, max_length=3, null=True)),
                ('prothr_hetero', models.CharField(blank=True, max_length=3, null=True)),
                ('prothr_homo', models.CharField(blank=True, max_length=3, null=True)),
                ('pai_ng', models.CharField(blank=True, max_length=3, null=True)),
                ('pai_hetero', models.CharField(blank=True, max_length=10, null=True)),
                ('pai_homo', models.CharField(blank=True, max_length=10, null=True)),
                ('mthfr_ng', models.CharField(blank=True, max_length=3, null=True)),
                ('mthfr_hetero', models.CharField(blank=True, max_length=3, null=True)),
                ('mthfr_homo', models.CharField(blank=True, max_length=3, null=True)),
                ('abort', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
