# Generated by Django 5.2.6 on 2025-10-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0018_pridacontroli'),
    ]

    operations = [
        migrations.CreateModel(
            name='PridaMutations2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('fvl_hetero', models.CharField(blank=True, max_length=3, null=True)),
                ('fvl_homo', models.CharField(blank=True, max_length=3, null=True)),
                ('prothr_hetero', models.CharField(blank=True, max_length=3, null=True)),
                ('prothr_homo', models.CharField(blank=True, max_length=3, null=True)),
                ('pai_hetero', models.CharField(blank=True, max_length=10, null=True)),
                ('pai_homo', models.CharField(blank=True, max_length=10, null=True)),
                ('mthfr_hetero', models.CharField(blank=True, max_length=3, null=True)),
                ('mthfr_homo', models.CharField(blank=True, max_length=3, null=True)),
                ('abort', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
