# Generated by Django 5.2.6 on 2025-10-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0019_pridamutations2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pridacontroli',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
