# Generated by Django 5.2.6 on 2026-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0020_pridacontroli_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridacontroli',
            name='abort',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pridamutations',
            name='abort',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pridamutations2',
            name='abort',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
