# Generated by Django 5.2.6 on 2026-05-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0021_alter_pridacontroli_abort_alter_pridamutations_abort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridamutations',
            name='id',
            field=models.PositiveSmallIntegerField(default=0, primary_key=1, serialize=False),
        ),
    ]
