# Generated by Django 5.2.6 on 2026-05-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0022_alter_pridamutations_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PridaPreeclampsia',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=0, primary_key=1, serialize=False)),
                ('patient', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sist_pressure', models.CharField(blank=True, max_length=5, null=True)),
                ('diasist_pressure', models.CharField(blank=True, max_length=5, null=True)),
                ('gw', models.CharField(blank=True, max_length=5, null=True)),
                ('weight', models.CharField(blank=True, max_length=5, null=True)),
                ('eai1', models.CharField(blank=True, max_length=5, null=True)),
                ('nea1', models.CharField(blank=True, max_length=5, null=True)),
                ('eai2', models.CharField(blank=True, max_length=5, null=True)),
                ('nea2', models.CharField(blank=True, max_length=5, null=True)),
                ('erythrocytes', models.CharField(blank=True, max_length=5, null=True)),
                ('hgb', models.CharField(blank=True, max_length=5, null=True)),
                ('hct', models.CharField(blank=True, max_length=5, null=True)),
                ('mch', models.CharField(blank=True, max_length=5, null=True)),
                ('mchc', models.CharField(blank=True, max_length=5, null=True)),
                ('rdw', models.CharField(blank=True, max_length=5, null=True)),
                ('prothrombin_time', models.CharField(blank=True, max_length=5, null=True)),
                ('prothrombin_time_percent', models.CharField(blank=True, max_length=5, null=True)),
                ('prothrombin_time_inr', models.CharField(blank=True, max_length=5, null=True)),
                ('plt', models.CharField(blank=True, max_length=5, null=True)),
                ('mpv', models.CharField(blank=True, max_length=5, null=True)),
                ('pct', models.CharField(blank=True, max_length=5, null=True)),
                ('pdw_percent', models.CharField(blank=True, max_length=5, null=True)),
                ('creatine_serum', models.CharField(blank=True, max_length=5, null=True)),
                ('total_protein_serum', models.CharField(blank=True, max_length=5, null=True)),
                ('albumin_serum', models.CharField(blank=True, max_length=5, null=True)),
                ('fibrinugen', models.CharField(blank=True, max_length=5, null=True)),
                ('crp', models.CharField(blank=True, max_length=5, null=True)),
                ('proetin_urine', models.CharField(blank=True, max_length=5, null=True)),
                ('asat', models.CharField(blank=True, max_length=5, null=True)),
                ('alat', models.CharField(blank=True, max_length=5, null=True)),
                ('mcv', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
