# Generated by Django 5.2.6 on 2026-05-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0023_pridapreeclampsia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
