# Generated by Django 5.2.6 on 2026-05-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0025_alter_pridapreeclampsia_alat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='prothrombin_time',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
