# Generated by Django 5.2.6 on 2026-05-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0026_alter_pridapreeclampsia_prothrombin_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='diasist_pressure',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='eai1',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='eai2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='erythrocytes',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='gw',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='hct',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='hgb',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='mch',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='mchc',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='mpv',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='nea1',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='nea2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='pct',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='pdw_percent',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='plt',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='prothrombin_time_inr',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='prothrombin_time_percent',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='rdw',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='sist_pressure',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='weight',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
