# Generated by Django 5.2.6 on 2026-05-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0027_alter_pridapreeclampsia_diasist_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='alat',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='albumin_serum',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='asat',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='creatine_serum',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='crp',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='fibrinugen',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='mcv',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='proetin_urine',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pridapreeclampsia',
            name='total_protein_serum',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
