# Generated by Django 5.2.6 on 2026-05-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0030_alter_pridapreeclampsia_alat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridacontroli',
            name='id',
            field=models.PositiveSmallIntegerField(default=0, primary_key=1, serialize=False),
        ),
    ]
