# Generated by Django 5.2.6 on 2026-05-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0031_alter_pridacontroli_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pridacontroli',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
