# Generated by Django 5.2.6 on 2026-06-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pridastartapp', '0032_alter_pridacontroli_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PridaPreeclampsiaCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sist_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('diasist_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('gw', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('eai1', models.CharField(blank=True, max_length=20, null=True)),
                ('nea1', models.CharField(blank=True, max_length=20, null=True)),
                ('eai2', models.CharField(blank=True, max_length=20, null=True)),
                ('nea2', models.CharField(blank=True, max_length=20, null=True)),
                ('erythrocytes', models.CharField(blank=True, max_length=20, null=True)),
                ('hgb', models.CharField(blank=True, max_length=20, null=True)),
                ('hct', models.CharField(blank=True, max_length=20, null=True)),
                ('mch', models.CharField(blank=True, max_length=20, null=True)),
                ('mchc', models.CharField(blank=True, max_length=20, null=True)),
                ('rdw', models.CharField(blank=True, max_length=20, null=True)),
                ('prothrombin_time', models.CharField(blank=True, max_length=20, null=True)),
                ('prothrombin_time_percent', models.CharField(blank=True, max_length=20, null=True)),
                ('prothrombin_time_inr', models.CharField(blank=True, max_length=20, null=True)),
                ('plt', models.CharField(blank=True, max_length=20, null=True)),
                ('mpv', models.CharField(blank=True, max_length=20, null=True)),
                ('pct', models.CharField(blank=True, max_length=20, null=True)),
                ('pdw_percent', models.CharField(blank=True, max_length=20, null=True)),
                ('creatine_serum', models.CharField(blank=True, max_length=20, null=True)),
                ('total_protein_serum', models.CharField(blank=True, max_length=20, null=True)),
                ('albumin_serum', models.CharField(blank=True, max_length=20, null=True)),
                ('fibrinugen', models.CharField(blank=True, max_length=20, null=True)),
                ('crp', models.CharField(blank=True, max_length=20, null=True)),
                ('proetin_urine', models.CharField(blank=True, max_length=20, null=True)),
                ('asat', models.CharField(blank=True, max_length=20, null=True)),
                ('alat', models.CharField(blank=True, max_length=20, null=True)),
                ('mcv', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
