# Generated by Django 5.0.7 on 2024-08-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maternal_age', models.IntegerField()),
                ('systolic_blood_pressure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diastolic_blood_pressure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gestational_week', models.DecimalField(decimal_places=1, max_digits=4)),
                ('newborn_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eai1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nea1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eai2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nea2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('erythrocytes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hematocrit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mcv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mch', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mchc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rdw', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prothrombin_time_sec', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prothrombin_time_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prothrombin_time_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('platelets', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mpv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pdw', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('creatinine', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_protein', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('albumin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fibrinogen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('crp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('proteinuria', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('asat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('factor_v_leiden', models.BooleanField(default=False)),
                ('factor_ii_mutation', models.BooleanField(default=False)),
                ('pai', models.BooleanField(default=False)),
                ('mthfr', models.BooleanField(default=False)),
            ],
        ),
    ]
