# Generated by Django 5.0.7 on 2024-09-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_controla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controla',
            name='newborn_weight',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
