# Generated by Django 5.0.7 on 2024-09-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_controla_newborn_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controla',
            name='newborn_weight',
            field=models.IntegerField(),
        ),
    ]
