# Generated by Django 5.0.7 on 2024-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_controla_newborn_weight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Controla',
            new_name='Control',
        ),
        migrations.AlterField(
            model_name='patient',
            name='newborn_weight',
            field=models.IntegerField(),
        ),
    ]
