# Generated by Django 5.1.2 on 2024-12-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_controla_control_alter_patient_newborn_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('year', models.PositiveIntegerField(verbose_name='Година')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('age', models.PositiveIntegerField(verbose_name='Възраст')),
                ('gender', models.CharField(choices=[('Male', 'Мъж'), ('Female', 'Жена')], max_length=10, verbose_name='Пол')),
                ('factor_v_normal', models.BooleanField(default=False, verbose_name='Factor V Leiden Normal Genotype')),
                ('factor_v_heterozygous', models.BooleanField(default=False, verbose_name='Heterozygous Factor V Leiden Mutation')),
                ('factor_v_homozygous', models.BooleanField(default=False, verbose_name='Homozygous Factor V Leiden Mutation')),
                ('factor_ii_normal', models.BooleanField(default=False, verbose_name='Factor II (Prothrombin) - Normal Genotype')),
                ('factor_ii_heterozygous', models.BooleanField(default=False, verbose_name='Factor II (Prothrombin) - Heterozygous Mutation')),
                ('factor_ii_homozygous', models.BooleanField(default=False, verbose_name='Factor II (Prothrombin) - Homozygous Mutation')),
                ('pai1_normal', models.BooleanField(default=False, verbose_name='PAI-1 Normal Genotype')),
                ('pai1_heterozygous', models.BooleanField(default=False, verbose_name='PAI-1 Heterozygous Mutation')),
                ('pai1_homozygous', models.BooleanField(default=False, verbose_name='PAI-1 Homozygous Mutation')),
                ('mthfr_normal', models.BooleanField(default=False, verbose_name='MTHFR Normal Genotype')),
                ('mthfr_heterozygous', models.BooleanField(default=False, verbose_name='MTHFR Heterozygous Mutation')),
                ('mthfr_homozygous', models.BooleanField(default=False, verbose_name='MTHFR Homozygous Mutation')),
            ],
            options={
                'verbose_name': 'Spontaneous Abortion',
                'verbose_name_plural': 'Spontaneous Abortions',
            },
        ),
    ]
