# Generated by Django 5.1.2 on 2024-12-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_abortion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abortion',
            options={},
        ),
        migrations.AddField(
            model_name='abortion',
            name='no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No'),
        ),
    ]
