# Generated by Django 5.1.2 on 2024-12-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_abortion_options_abortion_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abortion',
            name='factor_ii_heterozygous',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, verbose_name='Factor II (Prothrombin) - Heterozygous Mutation'),
        ),
        migrations.AlterField(
            model_name='abortion',
            name='factor_ii_homozygous',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, verbose_name='Factor II (Prothrombin) - Homozygous Mutation'),
        ),
        migrations.AlterField(
            model_name='abortion',
            name='factor_ii_normal',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, verbose_name='Factor II (Prothrombin) - Normal Genotype'),
        ),
        migrations.AlterField(
            model_name='abortion',
            name='factor_v_heterozygous',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, verbose_name='Heterozygous Factor V Leiden Mutation'),
        ),
        migrations.AlterField(
            model_name='abortion',
            name='factor_v_homozygous',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, verbose_name='Homozygous Factor V Leiden Mutation'),
        ),
        migrations.AlterField(
            model_name='abortion',
            name='factor_v_normal',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, verbose_name='Factor V Leiden Normal Genotype'),
        ),
        migrations.AlterField(
            model_name='abortion',
            name='mthfr_heterozygous',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, verbose_name='MTHFR Heterozygous Mutation'),
        ),
        migrations.AlterField(
            model_name='abortion',
            name='mthfr_homozygous',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, verbose_name='MTHFR Homozygous Mutation'),
        ),
        migrations.AlterField(
            model_name='abortion',
            name='mthfr_normal',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, verbose_name='MTHFR Normal Genotype'),
        ),
        migrations.AlterField(
            model_name='abortion',
            name='pai1_heterozygous',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, verbose_name='PAI-1 Heterozygous Mutation'),
        ),
        migrations.AlterField(
            model_name='abortion',
            name='pai1_homozygous',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, verbose_name='PAI-1 Homozygous Mutation'),
        ),
        migrations.AlterField(
            model_name='abortion',
            name='pai1_normal',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, verbose_name='PAI-1 Normal Genotype'),
        ),
    ]
